development:
  adapter: postgresql
  encoding: utf8
  database: hashtag_displayer_development
  pool: 5
  template: template0

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: hashtag_displayer_test
  pool: 5
  template: template0

production:
  adapter: postgresql
  encoding: utf8
  database: hashtag_displayer_production
  pool: 5
  template: template0
